'use client';
import React from 'react';
import Link from './link';
import {Check,ShieldCheck,Truck,PackageCheck,MapPin,Wallet,MessageCircle,Gamepad2,LoaderCircle} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {ContentText,useContent} from './content';
import {useStore} from './store';
export function SelectField({label,value,onChange,options,id}:{label:string;value:string;onChange:(v:string)=>void;options:string[]|{value:string;label:string}[];id:string}){return <div className="form-field"><label id={`${id}-label`} htmlFor={id}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger id={id} aria-labelledby={`${id}-label`} className="select-box"><SelectValue/></SelectTrigger><SelectContent>{options.map(x=>{const v=typeof x==='string'?x:x.value;return <SelectItem key={v} value={v}>{typeof x==='string'?x:x.label}</SelectItem>})}</SelectContent></Select></div>}
export function Field({label,id,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;id:string}){return <div className="form-field"><label htmlFor={id}>{label}</label><input id={id} {...props}/></div>}
export function Breadcrumbs({items}:{items:{label:string;url?:string}[]}){return <nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/"><ContentText text={"Home"}/></Link>{items.map((x,i)=><React.Fragment key={i}><span aria-hidden="true">/</span>{x.url?<Link href={x.url}>{x.label}</Link>:<span aria-current="page">{x.label}</span>}</React.Fragment>)}</nav>}
export function PageIntro({eyebrow,title,copy}:{eyebrow?:string;title:string;copy?:string}){return <div className="page-intro">{eyebrow&&<div className="eyebrow"><ContentText text={eyebrow}/></div>}<h1><ContentText text={title}/></h1>{copy&&<p><ContentText text={copy}/></p>}</div>}
export function SectionHead({eyebrow,title,copy,href,link}:{eyebrow?:string;title:string;copy?:string;href?:string;link?:string}){return <div className="section-head"><div>{eyebrow&&<div className="eyebrow"><ContentText text={eyebrow}/></div>}<h2><ContentText text={title}/></h2>{copy&&<p><ContentText text={copy}/></p>}</div>{href&&<Link className="text-link" href={href}><ContentText text={link||'Explore all'}/></Link>}</div>}
export function TrustBar(){return <div className="trust-bar"><div className="shell trust-items"><span><ShieldCheck/> <ContentText text={"Original seal promise"}/></span><span><MapPin/> 8+ years in Karachi</span><span><PackageCheck/> <ContentText text={"Clear warranty terms"}/></span><span><Wallet/> <ContentText text={"Ask about COD"}/></span><span><Truck/> <ContentText text={"Nationwide delivery"}/></span></div></div>}
export function SealFeature(){return <section className="seal-feature reveal"><div><div className="eyebrow"><ContentText text={"The GAME FROST difference"}/></div><h2><ContentText text={"Every console."}/><br/><ContentText text={"Original seal."}/><br/><span><ContentText text={"Peace of mind."}/></span></h2><p><ContentText text={"Pre-owned should never mean second guesses. See the seal, know the condition, and get the warranty in writing before you buy."}/></p><Link href="/why-the-seal-matters" className="text-link"><ContentText text={"Why the seal matters"}/></Link><div className="seal-points"><span><Check/> <ContentText text={"Unit-specific proof"}/></span><span><Check/> <ContentText text={"Clear inspection"}/></span></div></div><div className="seal-visual"><div className="seal-ring"><div className="seal-mark"><ShieldCheck size={48}/><strong><ContentText text={"ORIGINAL"}/><br/><ContentText text={"SEAL INTACT"}/></strong><span><ContentText text={"THE GAME FROST PROMISE"}/></span></div></div><div className="proof-label"><ContentText text={"A PROMISE BACKED BY THE EXACT UNIT’S EVIDENCE"}/></div></div></section>}
export function FAQ({limit}:{limit?:number}){const{faqs}=useContent();return <Accordion type="single" collapsible className="faq">{faqs.slice(0,limit??faqs.length).map((x,i)=><AccordionItem key={i} value={`${i}`}><AccordionTrigger>{x.q}</AccordionTrigger><AccordionContent>{x.a}</AccordionContent></AccordionItem>)}</Accordion>}
export function WhatsAppButton({text='WhatsApp us',message,className=''}:{text?:string;message?:string;className?:string}){const {inquire}=useStore();return <button className={`btn whatsapp ${className}`} onClick={()=>inquire(message)}><MessageCircle size={18}/><ContentText text={text}/></button>}
export function SaveButton({busy,text}:{busy:boolean;text:string}){return <button className="btn cyan full" disabled={busy} type="submit">{busy&&<LoaderCircle size={18} className="form-loader"/>}{busy?'Saving…':text}</button>}
export function Empty({title,copy,href,label}:{title:string;copy:string;href?:string;label?:string}){return <div className="empty-state"><Gamepad2 size={38}/><h3><ContentText text={title}/></h3><p><ContentText text={copy}/></p>{href&&<Link className="btn cyan" href={href}><ContentText text={label||'Browse consoles'}/></Link>}</div>}
