'use client';
import {lazy,Suspense} from 'react';
import {useContent} from './content';
import {productUrl} from '@/lib/catalog-helpers';
const ShowroomView=lazy(()=>import('./showroom').then(m=>({default:m.Showroom})));
const Home=lazy(()=>import('./home').then(m=>({default:m.Home})));
const Shop=lazy(()=>import('./shop').then(m=>({default:m.Shop}))),ProductDetail=lazy(()=>import('./shop').then(m=>({default:m.ProductDetail}))),GamesPage=lazy(()=>import('./shop').then(m=>({default:m.GamesPage}))),GameDetail=lazy(()=>import('./shop').then(m=>({default:m.GameDetail})));
const TradeIn=lazy(()=>import('./flows').then(m=>({default:m.TradeIn}))),Services=lazy(()=>import('./flows').then(m=>({default:m.Services}))),Cart=lazy(()=>import('./flows').then(m=>({default:m.Cart}))),Checkout=lazy(()=>import('./flows').then(m=>({default:m.Checkout}))),Account=lazy(()=>import('./flows').then(m=>({default:m.Account})));
const SealPage=lazy(()=>import('./pages').then(m=>({default:m.SealPage}))),About=lazy(()=>import('./pages').then(m=>({default:m.About}))),Visit=lazy(()=>import('./pages').then(m=>({default:m.Visit}))),Reviews=lazy(()=>import('./pages').then(m=>({default:m.Reviews}))),Guides=lazy(()=>import('./pages').then(m=>({default:m.Guides}))),FAQPage=lazy(()=>import('./pages').then(m=>({default:m.FAQPage}))),Policies=lazy(()=>import('./pages').then(m=>({default:m.Policies}))),BrandPage=lazy(()=>import('./pages').then(m=>({default:m.BrandPage})));
const Admin=lazy(()=>import('./admin').then(m=>({default:m.AdminPanel})));
const loaded:Record<string,any>={};
export async function preloadRoute(path:string){const kind=path==='/'?'home':path==='/admin'?'admin':path.startsWith('/shop')||path==='/new-games'||path.startsWith('/games/')?'shop':['/trade-in','/services','/jailbreak','/cart','/checkout','/account'].includes(path)?'flows':path.startsWith('/pages/')?'custom':'pages';if(kind==='home')loaded.home=await import('./home');else if(kind==='shop')loaded.shop=await import('./shop');else if(kind==='flows')loaded.flows=await import('./flows');else if(kind==='pages')loaded.pages=await import('./pages');else if(kind==='admin')loaded.admin=await import('./admin')}
function Missing(){return <main id="main" className="shell section"><h1>This room isn’t here.</h1><p>Explore the current lineup or return to the showroom.</p><a className="btn cyan" href="/shop">Browse the store</a></main>}
export function StorePage({path,query={}}:{path:string;query?:Record<string,string>}){const HomeView=loaded.home?.Home??Home,ShopView=loaded.shop?.Shop??Shop,ProductView=loaded.shop?.ProductDetail??ProductDetail,GamesView=loaded.shop?.GamesPage??GamesPage,GameView=loaded.shop?.GameDetail??GameDetail,TradeView=loaded.flows?.TradeIn??TradeIn,ServiceView=loaded.flows?.Services??Services,CartView=loaded.flows?.Cart??Cart,CheckoutView=loaded.flows?.Checkout??Checkout,AccountView=loaded.flows?.Account??Account,SealView=loaded.pages?.SealPage??SealPage,AboutView=loaded.pages?.About??About,VisitView=loaded.pages?.Visit??Visit,ReviewsView=loaded.pages?.Reviews??Reviews,GuidesView=loaded.pages?.Guides??Guides,FaqView=loaded.pages?.FAQPage??FAQPage,PoliciesView=loaded.pages?.Policies??Policies,BrandView=loaded.pages?.BrandPage??BrandPage,AdminView=loaded.admin?.AdminPanel??Admin;const{products,document,games,guides}=useContent();const p=products.find(p=>productUrl(p)===path);let view:React.ReactNode;
 if(p)view=<ProductView p={p}/>;else if(path==='/')view=<HomeView/>;else if(path==='/showroom')view=<main id="main"><ShowroomView/></main>;else if(path==='/shop')view=<ShopView query={query}/>;else if(path==='/trade-in')view=<TradeView query={query}/>;else if(path==='/services'||path==='/jailbreak')view=<ServiceView jailbreak={path==='/jailbreak'} query={query}/>;else if(path==='/cart')view=<CartView/>;else if(path==='/checkout')view=<CheckoutView/>;else if(path==='/account')view=<AccountView/>;else if(path==='/new-games')view=<GamesView/>;else if(path.startsWith('/games/')&&games.some(g=>g.id===path.split('/')[2]))view=<GameView id={path.split('/')[2]}/>;else if(path==='/why-the-seal-matters')view=<SealView/>;else if(path==='/about')view=<AboutView/>;else if(path==='/visit')view=<VisitView/>;else if(path==='/reviews')view=<ReviewsView/>;else if(path==='/guides'||path.startsWith('/guides/')&&guides.some(g=>g.slug===path.split('/')[2]))view=<GuidesView slug={path.split('/')[2]}/>;else if(path==='/faq')view=<FaqView/>;else if(path==='/policies')view=<PoliciesView/>;else if(path==='/brand')view=<BrandView/>;else if(path==='/admin')view=<AdminView/>;else {const page=document.pages.find(p=>p.visible&&path==='/pages/'+p.slug);view=page?<main id="main" className="shell section"><article className="prose"><div className="eyebrow">{page.eyebrow}</div><h1>{page.title}</h1><p>{page.summary}</p>{page.blocks.map((b,i)=><section key={i}>{b.heading&&<h2>{b.heading}</h2>}{b.text.split('\n').map((line,j)=><p key={j}>{line}</p>)}{b.image&&<img src={b.image} alt={b.heading||page.title} width="1200" height="800" loading="lazy" style={{width:'100%',height:'auto',borderRadius:12}}/>}</section>)}</article></main>:<Missing/>}
 return <Suspense fallback={<main id="main" className="shell section" aria-busy="true"><h1>{path==='/admin'?'Store manager':'Opening your next world.'}</h1></main>}>{view}</Suspense>}
