'use client';
import {ContentText} from './content';
import {useContent} from './content';
import {useEffect,useRef,useState} from 'react';
import {Gamepad2,Compass,Play,Pause,Volume2,VolumeX,Move,ChevronLeft,ChevronRight,ChevronUp,ChevronDown,ShoppingBag,Maximize,Minimize,RotateCcw,MousePointer2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import Link from './link';
import {useStore} from './store';
import {money,productUrl} from '@/lib/catalog-helpers';
import {type RoomId} from './showroom-data';
import type {ShowroomController} from './showroom-scene';

export function Showroom(){const {featuredProducts,rooms,products,document:content}=useContent();
 const [roomId,setRoomId]=useState<RoomId>('lobby');const[status,setStatus]=useState('idle');const[entered,setEntered]=useState(false);const[roam,setRoam]=useState(false);const[tour,setTour]=useState(false);const[motion,setMotion]=useState(true);const[sound,setSound]=useState(false);const[expanded,setExpanded]=useState(false);const[hover,setHover]=useState('');const[inspect,setInspect]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[position,setPosition]=useState({x:0,z:8.5});
 const host=useRef<HTMLDivElement>(null),controller=useRef<ShowroomController|null>(null),audio=useRef<AudioContext|null>(null),hold=useRef<ReturnType<typeof setInterval>|null>(null),root=useRef<HTMLElement>(null);const {add,inquire}=useStore();
 const room=rooms.find(x=>x.id===roomId)!;const product=products.find(p=>p.id===inspect);const shown=room.productIds.map(id=>products.find(p=>p.id===id)).filter((p):p is NonNullable<typeof p>=>!!p);
 useEffect(()=>{
  let gone=false;const media=matchMedia('(prefers-reduced-motion: reduce)');let animated=!media.matches;
  try{if(localStorage.getItem('gf-motion')==='off')animated=false;}catch{}
  setMotion(animated);const changed=()=>{if(media.matches)setMotion(false)};media.addEventListener('change',changed);
  if(!entered){return()=>media.removeEventListener('change',changed);}setStatus('loading');
  import('./showroom-scene').then(({mountShowroom})=>{if(gone||!host.current)return;try{controller.current=mountShowroom(host.current,{name:content.settings.name,motion:animated,quality:content.settings.quality,rooms,products:featuredProducts.filter(p=>p.image).slice(0,8),editorial:content.settings.editorial,onReady:()=>{if(!gone){setStatus('ready');controller.current?.go(roomId)}},onPick:id=>setInspect(id),onHover:setHover,onPosition:(x,z)=>setPosition({x,z}),onError:()=>{if(!gone){setStatus('fallback');setEntered(false);controller.current?.dispose();controller.current=null;setRoam(false);setTour(false);}}});}catch{setStatus('fallback')}}).catch(()=>{if(!gone){setStatus('fallback');setEntered(false)}});
  return()=>{gone=true;media.removeEventListener('change',changed);controller.current?.dispose();controller.current=null;audio.current?.close();if(hold.current)clearInterval(hold.current);document.documentElement.removeAttribute('data-showroom-expanded');};
 },[entered,content.settings.quality,rooms,featuredProducts,content.settings.editorial]);
 useEffect(()=>{if(content.settings.showroom!=='auto')return;const connection=(navigator as any).connection;if(connection?.saveData||/2g/.test(connection?.effectiveType||''))return;const timer=setTimeout(()=>setEntered(true),1800);return()=>clearTimeout(timer)},[content.settings.showroom]);
 useEffect(()=>{controller.current?.setMotion(motion);document.documentElement.dataset.motion=motion?'on':'off';window.dispatchEvent(new CustomEvent('gf-motion',{detail:motion}));try{localStorage.setItem('gf-motion',motion?'on':'off')}catch{}if(!motion)setTour(false);},[motion]);
 useEffect(()=>{if(!tour)return;const timer=setInterval(()=>setRoomId(previous=>{const next=rooms[(rooms.findIndex(r=>r.id===previous)+1)%rooms.length].id;controller.current?.go(next);return next}),6500);return()=>clearInterval(timer)},[tour]);
 useEffect(()=>{document.documentElement.dataset.showroomExpanded=expanded?'true':'false';const esc=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!document.querySelector('[data-slot=dialog-content]')){setExpanded(false);setRoam(false);controller.current?.setRoam(false);controller.current?.go(roomId)}};window.addEventListener('keydown',esc);return()=>window.removeEventListener('keydown',esc)},[expanded,roomId]);
 useEffect(()=>{if(!inspect)return;const wasRoam=roam;controller.current?.setRoam(false);return()=>{if(wasRoam)controller.current?.setRoam(true)}},[inspect]);
 function choose(id:RoomId){setTour(false);setRoam(false);controller.current?.setRoam(false);setRoomId(id);controller.current?.go(id);}
 function toggleRoam(){if(status==='idle'||status==='fallback'){setEntered(true);return;}if(status!=='ready')return;const active=!roam;setTour(false);setRoam(active);controller.current?.setRoam(active);if(!active)controller.current?.go(roomId);}
 async function toggleSound(){
  if(sound){await audio.current?.suspend();setSound(false);return;}
  try{if(!audio.current){const context=new AudioContext();audio.current=context;const gain=context.createGain();gain.gain.value=.022;gain.connect(context.destination);for(const [index,frequency] of [55,82.41,110].entries()){const osc=context.createOscillator();osc.type='sine';osc.frequency.value=frequency;osc.detune.value=index*2;osc.connect(gain);osc.start();}}await audio.current.resume();setSound(true);}catch{setSound(false);}
 }
 function stopHold(){if(hold.current){clearInterval(hold.current);hold.current=null;}}
 function beginMove(forward:number,side:number){stopHold();controller.current?.move(forward*.32,side*.32);hold.current=setInterval(()=>controller.current?.move(forward*.23,side*.23),85);}
 const roomIndex=rooms.findIndex(x=>x.id===roomId);const art=roomId==='retro'?'retro':roomId==='service'?'services':'lounge';
 return <>
 <section ref={root} id="showroom" className={`showroom ${status==='ready'?'is-ready':''} ${roam?'is-roaming':''} ${expanded?'is-expanded':''}`} style={{'--room-accent':room.color} as React.CSSProperties} aria-label="Interactive GAME FROST showroom">
  <div className="showroom-backdrop" aria-hidden="true"><img src={content.settings.editorial[art]||`/images/editorial/${art}-1536.webp`} srcSet={content.settings.editorial[art]?undefined:`/images/editorial/${art}-768.webp 768w, /images/editorial/${art}-1536.webp 1536w`} sizes="100vw" alt="" width="1536" height="1024" fetchPriority="high"/><div className="showroom-backdrop-shade"/></div>
  <div ref={host} className="showroom-canvas"/>
  <div className="showroom-vignette" aria-hidden="true"/>
  <div className="showroom-top"><span className="showroom-location"><span className="coordinate-line"/> <ContentText text={"KARACHI, PK · GAME FROST"}/></span><div className="showroom-tools">{roam&&<button className="room-tool" onClick={toggleRoam} aria-label="Exit free roam"><Compass size={16}/><span><ContentText text={"Exit roam"}/></span></button>}
   <button className="room-tool" onClick={()=>{setMotion(!motion)}} aria-label={motion?'Pause decorative motion':'Enable animated motion'} aria-pressed={motion}>{motion?<Pause size={15}/>:<Play size={15}/>}<span><ContentText text={"Motion"}/>{' '}{motion?'on':'off'}</span></button>
   <button className="room-tool" onClick={toggleSound} aria-label={sound?'Mute showroom ambience':'Enable showroom ambience'} aria-pressed={sound}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>}<span><ContentText text={"Sound"}/>{' '}{sound?'on':'off'}</span></button>
   <button className="room-tool" onClick={()=>{setExpanded(!expanded);if(!expanded)root.current?.scrollIntoView({behavior:'instant',block:'start'})}} aria-label={expanded?'Exit expanded showroom':'Expand showroom'}>{expanded?<Minimize size={17}/>:<Maximize size={17}/>}</button>
  </div></div>
  <div className="showroom-title" key={roomId}><div className="room-kicker"><span>{room.number}</span><span>{room.label}</span></div><h1>{room.title.split('\n').map((line,i)=><span key={line} className={i===1?'accent':''}>{line}</span>)}</h1><p>{room.copy}</p><div className="showroom-actions"><button className="btn room-primary" onClick={toggleRoam} disabled={status==='loading'}><Compass size={18}/>{status==='idle'?'Enter the 3D store':status==='loading'?'Opening…':roam?'Return to gallery':'Roam the store'}</button><Link className="showroom-shop-link" href={room.href}>{room.cta}</Link></div><span className="showroom-concept"><ContentText text={"A digital concept store · manufacturer product imagery"}/></span></div>
  <div className="room-map" aria-label="Showroom floor map"><div className="room-map-head"><span><ContentText text={"FLOOR / 01"}/></span><span>{roam?'FREE ROAM':tour?'GUIDED TOUR':'EXPLORE'}</span></div><div className="room-map-plan"><div className="room-map-aisle"/>{rooms.filter(r=>r.id!=='lobby').map(r=><button key={r.id} className={`map-zone map-${r.id} ${roomId===r.id?'active':''}`} aria-label={`Go to ${r.label}`} aria-pressed={roomId===r.id} onClick={()=>choose(r.id)}>{r.number}</button>)}<span className="map-you" style={{left:`${50+position.x/22*100}%`,top:`${12+(position.z+14)/26*76}%`}} aria-label="Your position"/><span className="map-entry"><ContentText text={"ENTRY"}/></span></div><div className="room-map-footer"><span><ContentText text={"Choose an area to move there."}/></span><button aria-label="Return to store entrance" onClick={()=>choose('lobby')}><RotateCcw size={13}/></button></div></div>
  <div className="showroom-product-shelf" aria-label={`${room.label} featured products`}>{shown.slice(0,2).map(p=><button key={p.id} className="room-product-chip" onClick={()=>setInspect(p.id)}><img src={p.image} alt="" width="70" height="55"/><span><strong>{p.name}</strong><small><ContentText text={"Inspect the model"}/></small></span><span className="chip-plus">+</span></button>)}</div>
  {roam&&<div className="roam-pad" aria-label="Move around the showroom">{[[1,0,'Forward',ChevronUp],[0,-1,'Left',ChevronLeft],[-1,0,'Back',ChevronDown],[0,1,'Right',ChevronRight]].map(([f,s,label,Icon])=>{const I=Icon as typeof ChevronUp;return <button key={String(label)} className={`pad-${String(label).toLowerCase()}`} aria-label={`Move ${String(label).toLowerCase()}`} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);beginMove(f as number,s as number)}} onPointerUp={stopHold} onPointerCancel={stopHold} onPointerLeave={stopHold} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();controller.current?.move((f as number)*.5,(s as number)*.5)}}}><I size={18}/></button>})}</div>}
  <div className="showroom-bottom"><div className="room-instructions">{status==='loading'?<><span className="opening-spinner"/> <ContentText text={"Opening the doors…"}/></>:status==='fallback'?<><Gamepad2 size={16}/> <ContentText text={"Choose an area to explore the collection."}/></>:roam?<><Move size={15}/><span><ContentText text={"Drag to look · WASD to walk · tap a display"}/></span></>:<><MousePointer2 size={15}/><span>{hover?`Inspect ${hover}`:'Choose a room or take the guided tour'}</span></>}</div><button className={`tour-button ${tour?'active':''}`} disabled={status==='loading'||!motion} onClick={()=>{if(status==='idle'){setEntered(true);return;}controller.current?.setRoam(false);setRoam(false);setTour(!tour)}}>{tour?<Pause size={15}/>:<Play size={15}/>} {tour?'Pause tour':'Take a tour'}</button><div className="room-pager"><button aria-label="Previous showroom area" onClick={()=>choose(rooms[(roomIndex+rooms.length-1)%rooms.length].id)}><ChevronLeft size={17}/></button><span>{String(roomIndex+1).padStart(2,'0')} <ContentText text={"/ 06"}/></span><button aria-label="Next showroom area" onClick={()=>choose(rooms[(roomIndex+1)%rooms.length].id)}><ChevronRight size={17}/></button></div></div>
  <nav className="room-navigation" aria-label="Store departments">{rooms.map(r=><button key={r.id} aria-pressed={roomId===r.id} className={roomId===r.id?'active':''} onClick={()=>choose(r.id)}><span>{r.number}</span>{r.label}</button>)}</nav>
 </section>
 <div className="frost-marquee" aria-hidden="true"><div>{[0,1].map(i=><span key={i}><ContentText text={"STEP INSIDE"}/>{' '}<span>✦</span> <ContentText text={"FIND YOUR WORLD"}/>{' '}<span>✦</span> <ContentText text={"GAME FROST"}/>{' '}<span>✦</span> <ContentText text={"PLAY IT YOUR WAY"}/>{' '}<span>✦</span> </span>)}</div></div>
 <Dialog open={!!product} onOpenChange={open=>{if(!open)setInspect(null)}}><DialogContent className="modal-content showroom-inspect"><DialogTitle>{product?.name}</DialogTitle><DialogDescription><ContentText text={"Manufacturer reference image. Price below is illustrative; confirm the exact unit before purchase."}/></DialogDescription>{product&&<><div className="inspect-stage"><div className="inspect-orbit"/><img className="inspect-photo" src={product.image} alt={product.name} width="600" height="450" onPointerMove={e=>{if(!motion||e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.transform=`perspective(800px) rotateY(${((e.clientX-r.left)/r.width-.5)*20}deg) rotateX(${((e.clientY-r.top)/r.height-.5)*-12}deg)`}} onPointerLeave={e=>e.currentTarget.style.transform=''}/></div><div className="inspect-details"><span className="eyebrow">{product.platform} · {product.storage}</span><strong>{product.price?money(product.price):'Ask for a quote'}</strong><p>{product.description}</p></div><div className="action-row"><Link href={productUrl(product)} className="btn room-primary"><ContentText text={"View model details"}/></Link><button className="btn secondary" disabled={busy} onClick={async()=>{if(!product.price){inquire(`Please share availability for ${product.name}.`);return;}setBusy(true);try{await add(product.id)}catch{}finally{setBusy(false)}}}><ShoppingBag size={17}/>{busy?'Adding…':'Add to sample cart'}</button></div></>}</DialogContent></Dialog>
 </>;
}
