'use client';
import {useEffect,useRef,useState} from 'react';
/** Native scrolling and small, optional enhancements keep content immediately available. */
export function SiteMotion(){const progress=useRef<HTMLDivElement>(null),cursor=useRef<HTMLDivElement>(null);const[enabled,setEnabled]=useState(false);
 useEffect(()=>{if(location.pathname.startsWith('/admin'))return;const media=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>setEnabled(!media.matches&&document.documentElement.dataset.motion!=='off');const custom=(e:Event)=>setEnabled((e as CustomEvent<boolean>).detail&&!media.matches);change();media.addEventListener('change',change);window.addEventListener('gf-motion',custom);return()=>{media.removeEventListener('change',change);window.removeEventListener('gf-motion',custom)}},[]);
 useEffect(()=>{if(!enabled)return;const nodes=Array.from(document.querySelectorAll<HTMLElement>('.reveal,.page-intro,.trade-promo,.story-grid'));const io=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){e.target.classList.add('motion-visible');io.unobserve(e.target)}},{rootMargin:'0px 0px 40px',threshold:.03});for(const node of nodes){if(node.getBoundingClientRect().top>innerHeight){node.classList.add('motion-reveal');io.observe(node)}}return()=>{io.disconnect();for(const node of nodes)node.classList.remove('motion-reveal','motion-visible')}},[enabled]);
 useEffect(()=>{let frame=0;const update=()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;const height=document.documentElement.scrollHeight-innerHeight;if(progress.current)progress.current.style.transform=`scaleX(${height>0?scrollY/height:0})`})};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[]);
 useEffect(()=>{if(!enabled||matchMedia('(pointer: coarse)').matches)return;let card:HTMLElement|null=null,frame=0;const reset=()=>{card?.style.removeProperty('--tilt-x');card?.style.removeProperty('--tilt-y');card=null;if(cursor.current)cursor.current.dataset.active='false'};const move=(e:PointerEvent)=>{if(frame||document.hidden)return;frame=requestAnimationFrame(()=>{frame=0;const target=e.target instanceof Element?e.target:null;const next=target?.closest<HTMLElement>('.product-card,.game-card,.platform-tile,.guide-card,.service-card')??null;if(next!==card){reset();card=next}if(!card)return;const r=card.getBoundingClientRect();card.style.setProperty('--tilt-x',`${(e.clientY-r.top-r.height/2)/r.height*-4}deg`);card.style.setProperty('--tilt-y',`${(e.clientX-r.left-r.width/2)/r.width*6}deg`);card.style.setProperty('--shine-x',`${(e.clientX-r.left)/r.width*100}%`);card.style.setProperty('--shine-y',`${(e.clientY-r.top)/r.height*100}%`);if(cursor.current){cursor.current.style.transform=`translate3d(${e.clientX}px,${e.clientY}px,0)`;cursor.current.dataset.active='true';cursor.current.textContent='EXPLORE'}})};document.addEventListener('pointermove',move,{passive:true});document.addEventListener('pointerleave',reset);window.addEventListener('blur',reset);return()=>{cancelAnimationFrame(frame);reset();document.removeEventListener('pointermove',move);document.removeEventListener('pointerleave',reset);window.removeEventListener('blur',reset)}},[enabled]);
 return <><div className="site-reading-progress" ref={progress} aria-hidden="true"/><div className="frost-cursor" ref={cursor} aria-hidden="true"/></>}
