import {z} from 'zod';
import {tradeEstimate} from '@/lib/catalog';
import {getPublished} from '@/lib/cms-server';
import {canPurchase,visibleProducts} from '@/lib/cms-model';
import {database,ownerFor,reply,sameOrigin} from '@/lib/store-server';
const line=z.object({id:z.string().max(100),qty:z.number().int().min(1).max(4)});
const cart=z.array(line).max(30);
const contact=z.object({name:z.string().trim().min(2).max(100),phone:z.string().regex(/^(?:\+92|0092|0)3\d{9}$/,'Enter a Pakistani mobile number, e.g. 03001234567.'),city:z.string().trim().min(2).max(100)});
export async function GET(request:Request){try{const {owner,user,cookie}=await ownerFor(request);const db=database();const [c,r]=await Promise.all([db.prepare('SELECT items FROM gf_carts WHERE owner=?').bind(owner).first<{items:string}>(),new URL(request.url).searchParams.get('view')==='cart'?Promise.resolve({results:[]}):db.prepare('SELECT id,kind,payload,created,status FROM gf_requests WHERE owner=? ORDER BY created DESC LIMIT 30').bind(owner).all()]);return reply({cart:c?JSON.parse(c.items):[],records:r.results.map((x:any)=>({...x,payload:JSON.parse(x.payload)})),user},200,cookie)}catch(e){console.error('Store load failed',e instanceof Error?e.message:'error');return reply({error:'Your saved items are temporarily unavailable. Please try again.'},503)}}
export async function POST(request:Request){if(!sameOrigin(request))return reply({error:'Request not allowed.'},403);try{if(Number(request.headers.get('content-length')||0)>32000)return reply({error:'Request too large.'},413);const raw=await request.text();if(raw.length>32000)return reply({error:'Request too large.'},413);const body:any=JSON.parse(raw);const submitted=z.boolean().optional().parse(body.submit)===true;const {owner,cookie}=await ownerFor(request);const db=database();const doc=await getPublished();const products=visibleProducts(doc),serviceTypes=doc.services;if(body.action==='cart'){const items=cart.parse(body.items);if(items.some(x=>!products.some(p=>p.id===x.id&&canPurchase(p))))return reply({error:'One of these products needs a quote first.'},400);const unique=Array.from(new Map(items.map(x=>[x.id,x])).values());await db.prepare('INSERT INTO gf_carts(owner,items,updated) VALUES(?,?,?) ON CONFLICT(owner) DO UPDATE SET items=excluded.items,updated=excluded.updated').bind(owner,JSON.stringify(unique),new Date().toISOString()).run();return reply({cart:unique},200,cookie)}
 if(body.action==='delete-draft'){const id=z.string().uuid().parse(body.id);await db.prepare("DELETE FROM gf_requests WHERE id=? AND owner=? AND status='draft'").bind(id,owner).run();return reply({ok:true},200,cookie)}
 const type=z.enum(['order','trade-in','service','inquiry','review']).parse(body.action);const id=z.string().uuid().parse(body.id);const previous=await db.prepare('SELECT owner,kind,status FROM gf_requests WHERE id=?').bind(id).first<{owner:string;kind:string;status:string}>();if(previous&&previous.owner!==owner)return reply({error:'Request not allowed.'},403);if(previous&&previous.kind!==type)return reply({error:'This reference belongs to another request type.'},409);if(previous&&previous.status!=='draft')return reply({id,status:previous.status,message:'Request already received. No payment has been collected.'},200,cookie);const payload=body.payload??{};let validated:any;
 if(type==='order'){const c=contact.extend({address:z.string().trim().min(8).max(500),payment:z.enum(['Cash on delivery','JazzCash','Easypaisa','Bank transfer']),items:cart}).parse(payload);if(!c.items.length)return reply({error:'Your cart is empty.'},400);if(new Set(c.items.map(x=>x.id)).size!==c.items.length)return reply({error:'Each product must appear once, with quantity up to four.'},400);const items=c.items.map(x=>{const p=products.find(p=>p.id===x.id&&canPurchase(p));if(!p)throw new z.ZodError([{code:'custom',path:['items'],message:'A selected product is no longer available. Review your cart.'}]);return{...x,name:p.name,price:p.price}});validated={...c,items,total:items.reduce((s,x)=>s+(x.price??0)*x.qty,0),delivery:'To be confirmed',sample:doc.settings.priceMode==='sample'};}
 else if(type==='trade-in'){const c=contact.extend({platform:z.enum(['PlayStation','Xbox','Nintendo']),model:z.string().max(80),seal:z.enum(['Original seal intact','Opened / broken seal','Not sure']),condition:z.enum(['Excellent','Good','Needs attention']),payout:z.enum(['Cash','Bank transfer','JazzCash','Easypaisa','Store credit']),handoff:z.enum(['Store drop-off','Karachi pickup']),notes:z.string().max(2000),photos:z.array(z.string().uuid()).max(4)}).parse(payload);const models:Record<string,string[]>={PlayStation:['PS5 Slim','PS5 Disc','PS4 Slim','PS4 Pro'],Xbox:['Xbox Series S','Xbox Series X'],Nintendo:['Switch OLED','Switch Lite']};if(!models[c.platform].includes(c.model))return reply({error:'Choose a model for the selected platform.'},400);for(const photo of c.photos){const r=await db.prepare('SELECT id FROM gf_uploads WHERE id=? AND owner=?').bind(photo,owner).first();if(!r)return reply({error:'A photo could not be verified. Please upload it again.'},400)}validated={...c,estimate:tradeEstimate(c.model,c.seal,c.condition),sample:doc.settings.priceMode==='sample'};}
 else if(type==='service'){const c=contact.extend({service:z.string().max(60),device:z.string().min(2).max(100),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T12:00:00Z');return !isNaN(d.getTime())&&d.toISOString().slice(0,10)===v},'Choose a valid date.'),notes:z.string().max(2000)}).parse(payload);const service=serviceTypes.find(x=>x.id===c.service);if(!service)return reply({error:'Choose a valid service.'},400);const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());if(c.date<today)return reply({error:'Choose today or a future date.'},400);validated={...c,serviceName:service.name,examplePrice:service.estimate,sample:doc.settings.priceMode==='sample'};}
 else if(type==='review'){validated=contact.extend({product:z.string().min(2).max(120),message:z.string().min(10).max(2000),videoUrl:z.string().url().max(500).optional().or(z.literal('')),consent:z.literal(true)}).parse(payload);}
 else validated=z.object({message:z.string().trim().min(3).max(2000)}).parse(payload);
 const now=new Date().toISOString(),status=submitted?'submitted':'draft';
 await db.prepare('INSERT INTO gf_requests(id,owner,kind,payload,created,status) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,owner,type,JSON.stringify(validated),now,status).run();
 if(submitted&&previous?.status==='draft')await db.prepare("UPDATE gf_requests SET payload=?,created=?,status='submitted' WHERE id=? AND owner=? AND status='draft'").bind(JSON.stringify(validated),now,id,owner).run();
 const stored=await db.prepare('SELECT owner,status FROM gf_requests WHERE id=?').bind(id).first<{owner:string;status:string}>();
 if(stored?.owner!==owner)return reply({error:'Request not allowed.'},403);
 return reply({id,status:stored.status,message:stored.status==='draft'?'Draft saved privately. Nothing has been submitted.':'Request received in the store queue. Final quote, stock and timing require owner confirmation. No payment has been collected.'},201,cookie);
 }catch(e){if(e instanceof z.ZodError)return reply({error:e.issues[0]?.message||'Please check your details.'},400);console.error('Store save failed',e instanceof Error?e.message:'error');return reply({error:'We could not save your draft. Your details are still here; please try again.'},503)}}
