export {money,productUrl,tradeEstimate} from './catalog-helpers';
export type Product={id:string;name:string;platform:string;category:string;price:number|null;compare?:number;image?:string;storage:string;color:string;condition:string;description:string;jailbroken:boolean;seal:boolean;specs:Record<string,string>;active?:boolean;featured?:boolean;stock?:'ask'|'available'|'preorder'|'sold-out'};

const p=(id:string,name:string,platform:string,category:string,price:number|null,image:string|undefined,storage:string,color='Black',extra:Partial<Product>={}):Product=>({id,name,platform,category,price,image:image?`/images/${image}.webp`:undefined,storage,color,condition:'Pre-owned',description:'Choose the exact unit after reviewing its condition photos, original-seal evidence and written warranty. Price and availability will be confirmed before purchase.',jailbroken:false,seal:category==='Consoles',specs:{'Model':name,'Storage':storage,'Condition':'Pre-owned · unit inspection required','Colour':color,'Seal evidence':'Actual-unit photo required before sale','Included accessories':'Confirmed on the unit’s written quote'},...extra});
export const featuredProducts:Product[]=[
 p('ps5-slim-disc','PlayStation 5 Slim Disc','PlayStation','Consoles',145000,'ps5-slim-disc','1TB','White',{compare:155000,description:'Disc or digital, your next chapter starts here. Explore the PS5 Slim Disc Edition with the original-seal inspection and a clear, unit-specific quote.'}),
 p('ps4-slim','PlayStation 4 Slim','PlayStation','Consoles',52000,'ps4-slim','500GB','Black',{compare:56000,description:'A big library. A smaller budget. A pre-owned PS4 Slim is an accessible way into PlayStation gaming, with condition and accessories agreed before purchase.'}),
 p('xbox-series-s','Xbox Series S','Xbox','Consoles',85000,'xbox-series-s','512GB','White',{compare:90000,description:'An all-digital console for a compact setup. Check available storage, region and account requirements before choosing your unit.'}),
 p('nintendo-switch-oled','Nintendo Switch OLED','Nintendo','Consoles',78000,'nintendo-switch-oled','64GB','White',{compare:82000,description:'At home or on the move. Ask about the exact unit, Joy-Con condition, dock, charger and screen before buying.'}),
 p('meta-quest-3','Meta Quest 3','Meta','VR & XR',135000,'meta-quest-3-cutout','512GB','White',{seal:false,description:'Step into mixed reality. Check the exact storage variant, lens condition, controllers and supported setup before ordering.'}),
 p('logitech-g29','Logitech G29 Racing Wheel','Logitech','Accessories',78000,'logitech-g29','N/A','Black',{condition:'New / pre-owned options',seal:false,description:'Build your next racing setup. Tell us your platform and game so we can confirm compatibility, pedals and mounting requirements.'}),
 p('steam-deck-oled','Steam Deck OLED','PC Handhelds','Consoles',155000,'steam-deck-oled-front','512GB','Black',{seal:false,description:'Your PC library, in your hands. Confirm game compatibility and the exact storage model before choosing a handheld.'}),
 p('dualsense-white','DualSense Wireless Controller','PlayStation','Accessories',18500,'dualsense-white','N/A','White',{seal:false,condition:'New / pre-owned options',description:'A second player changes everything. Ask about available colours, stick testing, battery condition and the included warranty.'}),
];
const otherModels:Record<string,{category:string;names:string[]}>= {
 PlayStation:{category:'Consoles',names:['PS5 Pro','PS5 Digital','PS5 Disc','PS5 Slim Digital','PlayStation Portal','PS4 Pro','PS4 Fat','PS3','PS2','PS1','PSP','PS Vita']},
 Xbox:{category:'Consoles',names:['Xbox Series X','ROG Xbox Ally','Xbox One X','Xbox One S','Xbox 360','Original Xbox']},
 Nintendo:{category:'Consoles',names:['Nintendo Switch 2','Nintendo Switch','Nintendo Switch Lite','Nintendo Wii U','Nintendo Wii','Nintendo GameCube','Nintendo 64','Super Nintendo SNES','Nintendo NES','Nintendo 3DS','Nintendo 2DS','Nintendo DS','Game Boy','Game Boy Color','Game Boy Advance']},
 'PC Handhelds':{category:'Consoles',names:['Steam Deck LCD','ROG Ally','Lenovo Legion Go']},
 Meta:{category:'VR & XR',names:['Meta Quest 3S','Ray-Ban Meta']},
 'VR & XR':{category:'VR & XR',names:['PlayStation VR2','Apple Vision Pro','Valve Index','XREAL smart glasses']},
 Accessories:{category:'Accessories',names:['Logitech G923','Thrustmaster racing wheels','Fanatec racing wheels','Pedals and shifters','Racing cockpits','Gaming headsets','Charging docks','HDMI and USB cables','Console cases']}
};
const retro=/PS3|PS2|PS1$|PSP|Vita|Xbox 360|Original Xbox|Wii|GameCube|Nintendo 64|SNES|NES|3DS|2DS|Nintendo DS|Game Boy/;
export const products=[...featuredProducts,...Object.entries(otherModels).flatMap(([platform,group])=>group.names.map(name=>p(name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),name,platform,retro.test(name)?'Retro':group.category,null,undefined,'Ask for variants','Varies',{seal:false})))];
export const platforms=['PlayStation','Xbox','Nintendo','PC Handhelds','Meta','Accessories'];
export const categories=['Consoles','Games','VR & XR','Accessories','Retro'];
export type Game={id:string;name:string;platform:string;image:string;status:string;release?:string;source:string;genre:string};
export const games:Game[]=[{"id": "gta-vi", "name": "Grand Theft Auto VI", "platform": "PS5 · Xbox Series X|S", "image": "/images/gta-vi.webp", "release": "2026-11-19", "status": "Coming soon", "source": "https://www.rockstargames.com/newswire/article/ak3ak31a49a221/grand-theft-auto-vi-is-now-set-to-launch-november-19-2026", "genre": "Action"}, {"id": "ea-sports-fc-27", "name": "EA SPORTS FC 27", "platform": "PS4 · PS5", "image": "/images/ea-sports-fc-27.webp", "release": "2026-09-25", "status": "Released", "source": "https://www.ea.com/games/ea-sports-fc/fc-27/news/fc-27-editions-and-release-dates", "genre": "Sports"}, {"id": "007-first-light", "name": "007 First Light", "platform": "PS5 · Xbox Series X|S", "image": "/images/007-first-light.webp", "release": "2026-05-27", "status": "Released", "source": "https://ioi.dk/007firstlightgame/news/2026/007-first-light-launches-globally", "genre": "Action"}, {"id": "resident-evil-requiem", "name": "Resident Evil Requiem", "platform": "PS5", "image": "/images/resident-evil-requiem.webp", "release": "2026-02-27", "status": "Released", "source": "https://www.playstation.com/en-us/games/resident-evil-requiem/", "genre": "Action"}, {"id": "ghost-of-yotei", "name": "Ghost of Yōtei", "platform": "PS5", "image": "/images/ghost-of-yotei.webp", "release": "2025-10-02", "status": "Released", "source": "https://www.playstation.com/en-us/games/ghost-of-yotei/", "genre": "Action"}, {"id": "spider-man-2", "name": "Marvel’s Spider-Man 2", "platform": "PS5", "image": "/images/spider-man-2.webp", "release": "2023-10-20", "status": "Released", "source": "https://www.playstation.com/en-us/games/marvels-spider-man-2/", "genre": "Action"}, {"id": "god-of-war-ragnarok", "name": "God of War Ragnarök", "platform": "PS4 · PS5", "image": "/images/god-of-war-ragnarok.webp", "release": "2022-11-09", "status": "Released", "source": "https://www.playstation.com/en-us/games/god-of-war-ragnarok/", "genre": "Action"}, {"id": "gran-turismo-7", "name": "Gran Turismo 7", "platform": "PS4 · PS5", "image": "/images/gran-turismo-7.webp", "release": "2022-03-04", "status": "Released", "source": "https://www.playstation.com/en-us/games/gran-turismo-7/", "genre": "Racing"}];
export const faqs=[
 {q:'What does “original seal intact” mean?',a:'It refers to the manufacturer’s tamper-evident seal on the console, where that model has one. It does not mean the retail box is unopened. Ask for a clear photo of the exact unit and its matching identification before purchase.'},
 {q:'Does an intact seal prove that a console has never been repaired?',a:'A seal is one useful part of the inspection, not a complete service history. We pair seal inspection with external condition and function checks. Replacement seals and differences between models need careful assessment.'},
 {q:'Can I pay cash on delivery?',a:'COD is part of the planned checkout. Eligibility, delivery fees and any advance charge must be confirmed for your city and order before payment. This preview does not dispatch orders or collect money.'},
 {q:'What does the store warranty cover?',a:'Your unit’s written quote should state the coverage, duration, exclusions and claim process. Those details must be agreed before purchase. The original-seal promise and the store’s hardware warranty are separate.'},
 {q:'How long does delivery take?',a:'The planned delivery window is same or next day in Karachi and 2–4 days for other Pakistani cities after confirmation. Courier coverage, stock and holidays can change the final estimate.'},
 {q:'Can I trade in a console with a broken seal?',a:'Yes, you can ask for an assessment. An opened unit is assessed separately and cannot qualify for the seal-intact range. Final trade value follows physical inspection, condition and accessory checks.'},
 {q:'Can you install games I own?',a:'Yes, request an installation or setup assessment for games you own or are licensed to use. Model, firmware and account compatibility are checked first. A compatible jailbreak is not available for every device or version.'},
 {q:'Are the prices and review cards on this site live?',a:'This is a store preview. Clearly labelled example prices demonstrate the shopping flow. Manufacturer images show models, not stock units. No customer names, ratings or testimonials have been invented.'}
];
export const serviceTypes=[{id:'jailbreak',name:'Jailbreak assessment',estimate:1500,copy:'Check your model and firmware before making changes. Compatibility, risks and a written quote come first.'},{id:'installation',name:'Game installation',estimate:1000,copy:'Install and organise games you own or are licensed to use. We confirm storage and account requirements.'},{id:'repairs',name:'Repairs & diagnostics',estimate:2000,copy:'Tell us what’s wrong. Inspection comes before any repair; opening a console changes its seal status.'},{id:'setup',name:'Console & racing setup',estimate:1500,copy:'From first-time console setup to wheel calibration, start with equipment compatibility and clear advice.'}];
export const guides=[
 {slug:'ps5-price-pakistan',tag:'Buying guide',title:'PS5 in Pakistan: new or pre-owned?',summary:'Look beyond the price. Compare condition, disc options, warranty and what’s in the box.',body:[['Start with the version','Disc, Digital, Slim and Pro are different choices. Compare the exact model and storage rather than treating every PS5 listing as the same product. Decide whether you want to buy or trade physical discs.'],['Compare the complete cost','Ask for a dated PKR quote that includes the console, controller, cables, delivery and the specific store warranty. A low listing price may not include the same accessories or coverage.'],['Inspect the exact pre-owned unit','Request clear photos, seal evidence where applicable, a matching unit reference, and a demonstration of startup, video output and controller function. A generic product photograph is not an inspection record.'],['Before paying','Read the return terms and confirm stock, region compatibility, delivery charges and payment recipient. Never treat a marketplace asking price as a guaranteed offer.']]},
 {slug:'original-seal-vs-opened-console',tag:'The seal guide',title:'An original seal. An informed choice.',summary:'What a seal tells you, what it doesn’t, and the checks worth asking for.',body:[['Seal-intact is not box-sealed','A pre-owned console can have an intact manufacturer seal even though its retail box has been opened. We use the terms separately so you know what you are buying.'],['Evidence before a label','Ask for a close-up photograph of the actual unit. The seal should be assessed alongside the model and unit identification. Designs differ between manufacturers and generations.'],['Look beyond the seal','An intact-looking label cannot establish the whole service history. External condition, ports, controller inputs and a functioning demonstration are separate evidence.'],['Opened consoles need different disclosure','Opening may be part of legitimate maintenance or repair. Ask what work was performed, which parts were replaced and what warranty remains. Opened stock should never be passed off as original-seal stock.']]},
 {slug:'first-racing-wheel-guide',tag:'Setup guide',title:'Your first racing wheel, without the guesswork.',summary:'Match your console, games and space before choosing a wheel.',body:[['Platform first','A wheel that works on one console family may not work on another. Check the exact model’s manufacturer compatibility list before ordering.'],['Plan the whole setup','Confirm whether pedals, a power supply and mounting hardware are included. A shifter, cockpit or wheel stand may be a separate purchase.'],['Make room for it','Measure your desk thickness, seat position and pedal space. Stable mounting matters to comfortable control.'],['Ask for a compatibility check','Tell GAME FROST your platform, wheel model and games. A written setup quote can avoid buying pieces that do not work together.']]}
];
export const routeMeta:Record<string,[string,string]>={
 '/':['GAME FROST | Enter Your Next World','Step into the GAME FROST gaming showroom. Explore consoles, handhelds, VR, retro and gaming gear. Buy, sell and trade in Karachi.'],
 '/shop':['Shop Consoles, Games & Accessories','Explore PlayStation, Xbox, Nintendo, handhelds, VR and gaming accessories. Compare models and request an exact-unit quote in Pakistan.'],
 '/services':['Console Services & Game Installation','Request console setup, game installation, jailbreak assessment or repair diagnostics in Karachi. Receive a clear quote before work begins.'],
 '/jailbreak':['Jailbreak Consoles & Compatibility Checks','Check model and firmware compatibility before booking a console jailbreak assessment. Explore installation and setup help in Karachi.'],
 '/trade-in':['Sell or Trade Your Console in Karachi','Get an indicative console trade-in range. Add condition photos and request an inspection for cash, bank transfer or store credit.'],
 '/reviews':['GAME FROST Customer Stories','See how GAME FROST collects genuine customer stories and submit your unboxing. Verified customer reviews will appear after approval.'],
 '/why-the-seal-matters':['Why the Original Console Seal Matters','Understand original seals, inspection evidence and the difference between seal-intact and box-sealed consoles before buying pre-owned.'],
 '/new-games':['New & Upcoming Games in Pakistan','Discover selected new and upcoming PlayStation, Xbox and Nintendo games. Check official release information and ask about availability.'],
 '/about':['About GAME FROST | Karachi Game Store','Eight-plus years of console conversations in Karachi. Meet the principles behind GAME FROST: clear condition, original-seal checks and support.'],
 '/guides':['Console Buying Guides for Pakistan','Straightforward guides to console prices, original seals, pre-owned units, VR and racing equipment for gamers in Pakistan.'],
 '/faq':['Frequently Asked Questions','Answers about seal checks, console trade-ins, store warranty, COD and delivery across Pakistan.'],
 '/visit':['Visit GAME FROST in Karachi','Plan a visit to GAME FROST in Karachi. Confirm the current store address, timings and exact-unit availability before you travel.'],
 '/cart':['Your Cart','Review your selected gaming products and example totals before saving an order draft.'],
 '/checkout':['Checkout Preview','Save a guest order draft. No payment is collected and no products are dispatched from this store preview.'],
 '/account':['Your GAME FROST Account','View your saved cart and order, service or trade-in drafts.'],
 '/brand':['GAME FROST Brand & Components','Explore the GAME FROST logo suite, design tokens, reusable components and motion direction.'],
 '/policies':['Warranty, Delivery & Privacy','Read how console quotes, warranty terms, delivery arrangements and preview data are handled.']
};
export function resolveProduct(path:string){return products.find(p=>path===`/shop/${p.platform.toLowerCase().replace(/[^a-z0-9]+/g,'-')}/${p.id}`)}

