import {createRequire} from 'node:module';
import {readFileSync,writeFileSync,realpathSync,readdirSync} from 'node:fs';
import {join,dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const require=createRequire(realpathSync(join(root,'node_modules/wrangler/package.json'))),{Miniflare}=require('miniflare');
const mf=new Miniflare({modulesRoot:join(root,'dist/server'),modules:[{type:'ESModule',path:join(root,'dist/server/index.js')},...readdirSync(join(root,'dist/server'),{recursive:true}).filter(p=>/\.m?js$/.test(p)&&p!=='index.js').map(p=>({type:'ESModule',path:join(root,'dist/server',p)}))],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'cms-tests'},r2Buckets:['BUCKET'],assets:{directory:join(root,'dist/client'),routerConfig:{has_user_worker:true}}});
const base='http://game-frost.test',owner={'oai-authenticated-user-id':'owner-test-identity','oai-authenticated-user-email':'kingasadkhan1556@gmail.com'},other={'oai-authenticated-user-id':'other-test-identity','oai-authenticated-user-email':'other@example.test'},checks=[];let calls=0;
async function call(path,headers={},data){calls++;const r=await mf.dispatchFetch(base+path,{method:data?'POST':'GET',headers:{...headers,...(data?{'Content-Type':'application/json',Origin:base}:{})},body:data?JSON.stringify(data):undefined});return r}
async function expect(path,status,headers={},data){const r=await call(path,headers,data);const j=await r.json();assert.equal(r.status,status,JSON.stringify(j));return j}
try{
 const db=await mf.getD1Database('DB');for(const name of readdirSync(join(root,'drizzle')).filter(n=>n.endsWith('.sql')).sort())for(const sql of readFileSync(join(root,'drizzle',name),'utf8').split('--> statement-breakpoint'))if(sql.trim())await db.exec(sql.replace(/\n/g,' '));
 await expect('/api/admin',403);await expect('/api/admin',403,other);await expect('/api/admin',403,{}, {action:'publish',revision:0,document:{}});await expect('/api/admin/media',403);checks.push('Anonymous visitors and other signed-in users cannot read drafts, publish changes or access the media editor.');
 const snapshot=await expect('/api/admin',200,owner);assert.equal(snapshot.revision,0);const original=structuredClone(snapshot.document),draft=structuredClone(original);draft.products[0].price=123456;draft.products[0].name='CMS verification console';draft.products[0].stock='available';draft.copy['Some games never get old.']='CMS verification retro headline';draft.faqs[0]={q:'CMS verification question',a:'A saved answer.'};draft.seo['/shop']=['CMS verification shop','An updated description.'];draft.pages.push({slug:'cms-verification',title:'CMS verification page',eyebrow:'New content',summary:'Published without editing code.',visible:true,blocks:[{heading:'First block',text:'Content written in the admin panel.',image:''}]});
 await expect('/api/admin',200,owner,{action:'save',revision:0,document:draft});assert.equal((await expect('/api/content',200)).products[0].price,145000);const saved=await expect('/api/admin',200,owner);assert.equal(saved.document.products[0].price,123456);assert.equal(saved.revision,1);checks.push('Draft changes survive separate requests and leave the public storefront unchanged.');
 await expect('/api/admin',409,owner,{action:'publish',revision:0,document:draft});const invalid=structuredClone(draft);invalid.navigation[0].href='javascript:alert(1)';await expect('/api/admin',400,owner,{action:'publish',revision:1,document:invalid});const cross=await mf.dispatchFetch(base+'/api/admin',{method:'POST',headers:{...owner,Origin:'http://evil.test','Content-Type':'application/json'},body:JSON.stringify({action:'publish',revision:1,document:{}})});assert.equal(cross.status,403);calls++;
 await expect('/api/admin',200,owner,{action:'publish',revision:1,document:draft});assert.equal((await expect('/api/content',200)).products[0].price,123456);for(const[path,text]of[['/shop/playstation/ps5-slim-disc','CMS verification console'],['/','CMS verification retro headline'],['/faq','CMS verification question'],['/shop','CMS verification shop'],['/pages/cms-verification','CMS verification page']]){const r=await call(path);assert.equal(r.status,200,path);assert.ok((await r.text()).includes(text),path)}const xml=await(await call('/sitemap.xml')).text();assert.ok(xml.includes('/pages/cms-verification'));checks.push('Published prices, product pages, copy, FAQs, metadata, new pages and sitemap update immediately; stale saves and unsafe links are rejected.');
 const store=await call('/api/store');const cookie=store.headers.get('set-cookie').split(';')[0];const orderId=crypto.randomUUID();await expect('/api/store',201,{Cookie:cookie},{action:'order',id:orderId,payload:{name:'CMS Test',phone:'03001234567',city:'Karachi',address:'Test address only',payment:'Cash on delivery',items:[{id:'ps5-slim-disc',qty:2,price:1}],total:2}});const state=await expect('/api/store',200,{Cookie:cookie});assert.equal(state.records[0].payload.total,246912);const sold=structuredClone(draft);sold.products[0].stock='sold-out';await expect('/api/admin',200,owner,{action:'publish',revision:2,document:sold});await expect('/api/store',400,{Cookie:cookie},{action:'cart',items:[{id:'ps5-slim-disc',qty:1}]});checks.push('Order totals use published CMS prices; a client cannot spoof prices, and sold-out products cannot be added.');
 const history=await expect('/api/admin',200,owner);assert.equal(history.history.length,2);await expect('/api/admin',200,owner,{action:'restore',revision:3,id:history.history[1].id});assert.equal((await expect('/api/admin',200,owner)).document.products[0].stock,'available');assert.equal((await expect('/api/content',200)).products[0].stock,'sold-out');checks.push('A published version restores to a draft and does not unexpectedly overwrite the live store.');
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2nWQAAAAASUVORK5CYII=','base64');const form=new FormData();form.set('file',new Blob([png],{type:'image/png'}),'test.png');const request=new Request(base+'/api/admin/media',{method:'POST',body:form});const up=await mf.dispatchFetch(base+'/api/admin/media',{method:'POST',headers:{...owner,Origin:base,'Content-Type':request.headers.get('content-type')},body:await request.arrayBuffer()});calls++;assert.equal(up.status,201);const image=await up.json();const publicImage=await call(image.url);assert.equal(publicImage.status,200);assert.equal(publicImage.headers.get('content-type'),'image/png');assert.ok(publicImage.headers.get('cache-control').includes('immutable'));assert.equal((await publicImage.arrayBuffer()).byteLength,png.length);const form2=new FormData();form2.set('file',new Blob(['<svg><script>alert(1)</script></svg>'],{type:'image/svg+xml'}),'bad.svg');const request2=new Request(base+'/api/admin/media',{method:'POST',body:form2});const bad=await mf.dispatchFetch(base+'/api/admin/media',{method:'POST',headers:{...owner,Origin:base,'Content-Type':request2.headers.get('content-type')},body:await request2.arrayBuffer()});assert.equal(bad.status,400);calls++;checks.push('Owner uploads persist in R2 and load with immutable caching; executable SVG uploads are rejected.');
 const denied=await call('/admin');assert.ok((await denied.text()).includes('Store owner access'));const allowed=await call('/admin',owner);assert.equal(allowed.status,200);assert.ok((await allowed.text()).includes('Opening your store manager'));checks.push('The hosted admin page checks owner identity before rendering the editor.');
 const result={date:new Date().toISOString(),apiAndRenderRequests:calls,checks,browserQA:'See hosted-browser-verification.json. This suite uses built Worker/D1/R2 requests; no physical phone FPS or field Web Vitals claim.'};writeFileSync(join(root,'docs/cms-verification.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
}finally{await mf.dispose()}
