"""Run against tools/hosted-qa-server.mjs only (isolated loopback mock identity)."""
import json
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];BASE='http://127.0.0.1:4176';OUT=ROOT/'outputs/preview';OUT.mkdir(parents=True,exist_ok=True)
r={'scope':'Built Worker, isolated D1/R2, loopback-only QA mock identity; actual production dispatch login not exercised.','checks':[],'errors':[]}
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox']);owner=b.new_context(viewport={'width':1440,'height':1000});owner.add_cookies([{'name':'gf_qa_owner','value':'yes','url':BASE}]);customer=b.new_context(viewport={'width':390,'height':844});a=owner.new_page();c=customer.new_page()
 for pg in [a,c]:pg.on('pageerror',lambda e:r['errors'].append(str(e)))
 path='/shop/playstation/ps5-slim-disc';c.goto(BASE+path,wait_until='networkidle');original=c.locator('main h1').inner_text();a.goto(BASE+'/admin',wait_until='networkidle');a.locator('.cms-sidebar').get_by_role('button',name='Products').click();a.get_by_role('button',name='Edit',exact=True).first.click();a.get_by_label('Product name',exact=True).fill('QA PS5 shared product');a.get_by_role('button',name='Apply to draft',exact=True).click();a.get_by_role('dialog').wait_for(state='hidden');a.get_by_role('button',name='Save draft',exact=True).click();a.wait_for_function('document.querySelector(".cms-save-status")?.textContent.includes("Draft saved")');assert not a.locator('.cms-save-status').evaluate("e=>e.classList.contains('unsaved')");c.reload(wait_until='networkidle');assert c.locator('main h1').inner_text()==original
 a.get_by_role('button',name='Publish changes',exact=True).click();a.wait_for_function('document.querySelector(".cms-save-status")?.textContent.includes("Draft saved")');c.reload(wait_until='networkidle');assert c.locator('main h1').inner_text()=='QA PS5 shared product';r['checks'].append('Actual product edit: save leaves independent visitor unchanged, normalized save shows clean state, publish reaches independent visitor.')
 a.get_by_role('button',name='FAQs',exact=True).click();a.get_by_label('Question',exact=True).first.fill('QA shared FAQ question?');a.get_by_role('button',name='Publish changes',exact=True).click();a.wait_for_function('document.querySelector(".cms-save-status")?.textContent.includes("Draft saved")');c.goto(BASE+'/faq',wait_until='networkidle');assert 'QA shared FAQ question?' in c.locator('main').inner_text();r['checks'].append('Actual FAQ edit and publish reach an independent browser session.')
 c.goto(BASE+path,wait_until='networkidle');c.get_by_role('button',name='Add to cart',exact=True).first.click();c.goto(BASE+'/checkout',wait_until='networkidle')
 for field,value in [('contact-phone','03001234567'),('contact-name','QA Customer'),('contact-city','Karachi'),('contact-address','QA address, test only')]:c.locator('#'+field).fill(value)
 c.get_by_role('checkbox').check();c.get_by_role('button',name='Request a final quote',exact=True).click();c.wait_for_selector('.confirmation');assert 'Request received' in c.locator('.confirmation').inner_text();r['checks'].append('Actual hosted checkout submits a quote request with no payment or reservation claim.')
 a.get_by_role('button',name='Customer requests',exact=True).click();a.get_by_label('Owner workflow status',exact=True).first.wait_for();a.get_by_label('Owner workflow status',exact=True).first.select_option('reviewing');a.wait_for_function('document.querySelector("select[id^=status-]")?.value==="reviewing"');a.get_by_label('Owner workflow status',exact=True).first.wait_for(state='visible');a.screenshot(path=str(OUT/'hosted-owner-queue-desktop.png'),full_page=True);a.set_viewport_size({'width':390,'height':844});a.screenshot(path=str(OUT/'hosted-owner-queue-mobile.png'),full_page=True)
 c.goto(BASE+'/account',wait_until='networkidle');c.get_by_text('ORDER REVIEWING',exact=True).wait_for();r['checks'].append('Owner queue receives the customer submission and an actual status edit reaches the customer account.')
 status=c.evaluate("async()=>{const r=await fetch('/api/admin/requests');return r.status}");assert status==403;c.goto(BASE+'/admin',wait_until='networkidle');assert 'owner' in c.locator('main').inner_text().lower();assert c.get_by_role('button',name='Products',exact=True).count()==0;r['checks'].append('Anonymous browser cannot open the owner editor or merchant queue.')
 owner.close();customer.close();b.close()
(ROOT/'docs/hosted-browser-verification.json').write_text(json.dumps(r,indent=2));print(json.dumps(r),flush=True)
