import type {StoreDocument} from '../lib/cms-model';
import {productUrl} from '../lib/catalog-helpers';
import {scenesFor} from '../lib/scenes';
export type ZipEntry={name:string;bytes:Uint8Array};
const encoder=new TextEncoder();
const crcTable=Array.from({length:256},(_,value)=>{for(let k=0;k<8;k++)value=value&1?0xedb88320^(value>>>1):value>>>1;return value>>>0});
function crc32(bytes:Uint8Array){let crc=0xffffffff;for(const b of bytes)crc=crcTable[(crc^b)&255]^(crc>>>8);return(crc^0xffffffff)>>>0}
/** Small uncompressed ZIP writer. Only loaded when the owner requests an export. */
export function makeZip(entries:ZipEntry[]):Uint8Array{const chunks:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0,size=0;for(const{name,bytes}of entries){if(name.startsWith('/')||name.split('/').includes('..'))throw new Error('Invalid archive path.');const filename=encoder.encode(name),crc=crc32(bytes);const local=new Uint8Array(30+filename.length),l=new DataView(local.buffer);l.setUint32(0,0x04034b50,true);l.setUint16(4,20,true);l.setUint16(6,0x0800,true);l.setUint32(14,crc,true);l.setUint32(18,bytes.length,true);l.setUint32(22,bytes.length,true);l.setUint16(26,filename.length,true);local.set(filename,30);chunks.push(local,bytes);const row=new Uint8Array(46+filename.length),c=new DataView(row.buffer);c.setUint32(0,0x02014b50,true);c.setUint16(4,20,true);c.setUint16(6,20,true);c.setUint16(8,0x0800,true);c.setUint32(16,crc,true);c.setUint32(20,bytes.length,true);c.setUint32(24,bytes.length,true);c.setUint16(28,filename.length,true);c.setUint32(42,offset,true);row.set(filename,46);central.push(row);size+=row.length;offset+=local.length+bytes.length;}const end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,entries.length,true);v.setUint16(10,entries.length,true);v.setUint32(12,size,true);v.setUint32(16,offset,true);const zip=new Uint8Array(offset+size+22);let cursor=0;for(const chunk of[...chunks,...central,end]){zip.set(chunk,cursor);cursor+=chunk.length}return zip}
const escape=(value:string)=>value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
export function documentPaths(doc:StoreDocument){return[...new Set([...Object.keys(doc.seo),'/admin',...doc.products.filter(p=>p.active!==false).map(productUrl),...doc.games.map(g=>'/games/'+g.id),...doc.guides.map(g=>'/guides/'+g.slug),...doc.pages.filter(p=>p.visible).map(p=>'/pages/'+p.slug)])]}
export function htmlForPath(template:string,path:string,doc:StoreDocument){const product=doc.products.find(p=>productUrl(p)===path),game=doc.games.find(g=>'/games/'+g.id===path),guide=doc.guides.find(g=>'/guides/'+g.slug===path),page=doc.pages.find(p=>'/pages/'+p.slug===path);const title=(path==='/not-found'?'Page not found':undefined)||doc.seo[path]?.[0]||product?.name||game?.name||guide?.title||page?.title||doc.settings.name;const description=doc.seo[path]?.[1]||product?.description||guide?.summary||page?.summary||doc.settings.tagline;let html=template.replace(/<title>[\s\S]*?<\/title>/i,'<title>'+escape(title)+'</title>').replace(/<meta\b[^>]*name="description"[^>]*>/i,'');html=html.replace('</head>',`<meta name="description" content="${escape(description)}"/></head>`);html=html.replace(/<body[^>]*>[\s\S]*?<\/body>/i,`<body><div id="root"><main style="padding:60px;font:16px Arial"><h1>${escape(title)}</h1><p>Opening ${escape(doc.settings.name)}…</p></main></div><noscript>Please enable JavaScript to explore this store.</noscript></body>`);return html}
export async function exportNetlify(input:StoreDocument,local:boolean,onProgress:(v:number)=>void){const{documentSchema}=await import('../lib/cms-validation');const doc=documentSchema.parse(structuredClone(input)) as StoreDocument,prefix=local?'':'/admin-kit';const manifestResponse=await fetch(prefix+'/export-manifest.json');if(!manifestResponse.ok)throw new Error('The export files are unavailable. Please reload and try again.');const manifest=await manifestResponse.json() as{files:string[]};const entries:ZipEntry[]=[],images=new Map<string,string>();
 // Move uploaded public images into the portable package. Customer photos are never included.
 const convert=async(value:string)=>{if(!value||!value.startsWith('data:image/')&&!value.startsWith('/media/'))return value;if(images.has(value))return images.get(value)!;const r=await fetch(value);if(!r.ok)throw new Error('An uploaded image could not be exported. Try uploading it again.');const bytes=new Uint8Array(await r.arrayBuffer());const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes as BufferSource))).map(b=>b.toString(16).padStart(2,'0')).join('').slice(0,20);const type=r.headers.get('content-type');const name='images/uploads/'+digest+(type?.includes('png')?'.png':type?.includes('jpeg')?'.jpg':'.webp');entries.push({name,bytes});const url='/'+name;images.set(value,url);return url};
 for(const p of doc.products)if(p.image)p.image=await convert(p.image);for(const g of doc.games)g.image=await convert(g.image);for(const p of doc.pages)for(const b of p.blocks)b.image=await convert(b.image);for(const key of Object.keys(doc.settings.editorial) as('lounge'|'services'|'retro')[])doc.settings.editorial[key]=await convert(doc.settings.editorial[key]);
 doc.scenes=scenesFor(doc);for(const scene of doc.scenes)scene.poster=await convert(scene.poster);
 const files=manifest.files.filter(name=>!name.endsWith('.html')&&!['store-content.json','export-manifest.json','sitemap.xml'].includes(name));let completed=0;await Promise.all(Array.from({length:Math.min(5,files.length)},async()=>{while(completed<files.length){const index=completed++;const name=files[index];const r=await fetch(prefix+'/'+name);if(!r.ok)throw new Error('Could not export '+name);entries.push({name,bytes:new Uint8Array(await r.arrayBuffer())});onProgress(10+completed/files.length*65)}}));const template=await(await fetch(prefix+'/index.html')).text();const paths=documentPaths(doc);for(const path of paths)entries.push({name:(path==='/'?'':path.slice(1)+'/')+'index.html',bytes:encoder.encode(htmlForPath(template,path,doc))});entries.push({name:'404.html',bytes:encoder.encode(htmlForPath(template,'/not-found',doc))},{name:'store-content.json',bytes:encoder.encode(JSON.stringify(doc))});const publicPaths=paths.filter(p=>!['/admin','/account','/cart','/checkout','/brand'].includes(p));entries.push({name:'sitemap.xml',bytes:encoder.encode('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+publicPaths.map(p=>`<url><loc>${escape(location.origin+p)}</loc></url>`).join('')+'</urlset>')});entries.push({name:'export-manifest.json',bytes:encoder.encode(JSON.stringify({files:[...new Set([...entries.map(e=>e.name),'export-manifest.json'])]}))});const unique=Array.from(new Map(entries.map(e=>[e.name,e])).values());onProgress(90);const zip=makeZip(unique);const blob=new Blob([zip as BlobPart],{type:'application/zip'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='GAME-FROST-Netlify-Updated.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);onProgress(100)}
