import type {CmsSnapshot,StoreDocument} from '../lib/cms-model';
import {read,mutate} from './browser-db';
type LocalSnapshot=CmsSnapshot&{baseHash:string;versions:{id:string;action:string;created:string;content:StoreDocument}[]};
let original:StoreDocument,baseHash='';
const defaultSnapshot=():LocalSnapshot=>({document:original,published:original,revision:0,updated:null,history:[],local:true,baseHash,versions:[]});
export async function loadLocalContent(doc:StoreDocument){original=doc;const bytes=new TextEncoder().encode(JSON.stringify(doc));baseHash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(b=>b.toString(16).padStart(2,'0')).join('');try{const stored=await read<LocalSnapshot|null>('cms',null);if(stored&&stored.baseHash===baseHash)return stored.published;if(stored&&stored.baseHash!==baseHash){await mutate('cms',defaultSnapshot(),old=>({...old,published:doc,document:JSON.stringify(old.document)===JSON.stringify(old.published)?doc:old.document,baseHash,revision:old.revision+1}));}return doc}catch{return doc}}
export async function currentContent(){return(await read('cms',defaultSnapshot())).published}
function reply(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
export async function handleLocalCms(req:Request){try{const path=new URL(req.url).pathname;if(path==='/api/admin'&&req.method==='GET'){const s=await read('cms',defaultSnapshot());const{versions,baseHash:hash,...publicSnapshot}=s;return reply(publicSnapshot)}if(path==='/api/admin'&&req.method==='POST'){const body=await req.json() as any;if(!['save','publish','restore'].includes(body.action))throw new Error('Unknown editor action.');const{documentSchema}=await import('../lib/cms-validation');const now=new Date().toISOString();const id=crypto.randomUUID();const result=await mutate('cms',defaultSnapshot(),s=>{if(body.revision!==s.revision)throw new Error('Another tab saved a newer version. Download your backup, then reload before saving.');const candidate=body.action==='restore'?s.versions.find(v=>v.id===body.id)?.content:body.document;if(!candidate)throw new Error('The selected version is unavailable.');const document=documentSchema.parse(candidate) as StoreDocument;const published=body.action==='publish';const versions=published?[{id,action:'Published',created:now,content:document},...s.versions].slice(0,12):s.versions;return{...s,document,published:published?document:s.published,versions,history:versions.map(({id,action,created})=>({id,action,created})),revision:s.revision+1,updated:now}});return reply({ok:true,document:result.document,published:body.action==='publish',revision:result.revision,updated:now,message:body.action==='publish'?'Changes applied on this device. Export to update Netlify.':body.action==='restore'?'Version restored to draft.':'Draft saved on this device.'})}
 if(path==='/api/admin/media'&&req.method==='GET')return reply({media:await read('cms-media',[])});
 if(path==='/api/admin/media'&&req.method==='POST'){const file=(await req.formData()).get('file');if(!(file instanceof File)||file.size>5*1024*1024)throw new Error('Choose an image under 5 MB.');const buffer=new Uint8Array(await file.arrayBuffer());const decoder=new TextDecoder();const valid=buffer[0]===137&&buffer[1]===80&&buffer[2]===78&&buffer[3]===71||buffer[0]===255&&buffer[1]===216&&buffer[2]===255||decoder.decode(buffer.slice(0,4))==='RIFF'&&decoder.decode(buffer.slice(8,12))==='WEBP';if(!valid)throw new Error('Choose a JPG, PNG or WebP image.');const url=await new Promise<string>((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(String(f.result));f.onerror=()=>reject(new Error('Image could not be saved.'));f.readAsDataURL(file)});const item={id:crypto.randomUUID(),name:file.name,url,mime:file.type,size:file.size,created:new Date().toISOString()};await mutate<any[]>('cms-media',[],items=>[item,...items].slice(0,200));return reply(item,201)}return reply({error:'Unknown local editor operation.'},404)}catch(e){return reply({error:e instanceof Error?e.message:'Please retry.'},e instanceof Error&&e.message.startsWith('Another tab')?409:400)}}
